# Generated by Django 5.0.6 on 2024-07-12 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Инструмент')),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('genre', models.ManyToManyField(to='genres.genre', verbose_name='Жанр')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicians.instrument', verbose_name='Инструмент')),
            ],
            options={
                'verbose_name': 'Музыкант',
                'verbose_name_plural': 'Музыканты',
            },
        ),
    ]
