# Generated by Django 5.0.6 on 2024-07-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
        migrations.AlterModelOptions(
            name='musician',
            options={'verbose_name': 'Музыкант', 'verbose_name_plural': 'Музыканты'},
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Инструмент'),
        ),
    ]
