# Generated by Django 5.0.6 on 2024-07-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(upload_to='genres/images/', verbose_name='Изображение'),
        ),
    ]
